/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.11 /Users/benjaminkonig/code/visualizer/public/forest_tree.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/forest_tree.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.SimpleGround.geometry} material={materials.AllColors_Material} />
      <mesh geometry={nodes.Tree_average_bare.geometry} material={materials.AllColors_Material} position={[-15.2, 0, -10.98]} />
      <mesh geometry={nodes.Tree_average_regular.geometry} material={materials.AllColors_Material} position={[0.18, 0, -10.98]} />
      <mesh geometry={nodes.Tree_average_lush.geometry} material={materials.AllColors_Material} position={[17.34, 0, -10.98]} />
      <mesh geometry={nodes.Tree_small_regular.geometry} material={materials.AllColors_Material} position={[-24.29, 0, -11.03]} />
      <mesh geometry={nodes.Tree_small_bare.geometry} material={materials.AllColors_Material} position={[-27.45, 0, -11.03]} />
      <mesh geometry={nodes.Tree_Spruce_small_02.geometry} material={materials.AllColors_Material} position={[23.72, 0, 1.82]} />
      <mesh geometry={nodes.Tree_Spruce_tiny_01.geometry} material={materials.AllColors_Material} position={[-7.53, 0, 1.82]} />
      <mesh geometry={nodes.Tree_Spruce_tiny_02.geometry} material={materials.AllColors_Material} position={[0.37, 0, 1.82]} />
      <mesh geometry={nodes.Tree_Spruce_small_01.geometry} material={materials.AllColors_Material} position={[11.07, 0, 1.82]} />
      <mesh geometry={nodes.Bush_average.geometry} material={materials.AllColors_Material} position={[2.22, 0, 12.32]} />
      <mesh geometry={nodes.Bush_average_bare.geometry} material={materials.AllColors_Material} position={[-3.19, 0, 12.32]} />
      <mesh geometry={nodes.Bush_group_average.geometry} material={materials.AllColors_Material} position={[13.38, 0, 12.78]} />
      <mesh geometry={nodes.Bush_group_big.geometry} material={materials.AllColors_Material} position={[20.33, 0, 12.78]} />
      <mesh geometry={nodes.Bush_group_small.geometry} material={materials.AllColors_Material} position={[7.72, 0, 12.78]} />
      <mesh geometry={nodes.Stump_average_high.geometry} material={materials.AllColors_Material} position={[-14.39, 0, 0.77]} />
      <mesh geometry={nodes.Stump_average_flat.geometry} material={materials.AllColors_Material} position={[-24.34, 0, 0.77]} />
      <mesh geometry={nodes.Stump_average_low.geometry} material={materials.AllColors_Material} position={[-21.03, 0, 0.77]} />
      <mesh geometry={nodes.Stump_average_hollow.geometry} material={materials.AllColors_Material} position={[-17.68, 0, 0.77]} />
      <mesh geometry={nodes.Log_big_regular.geometry} material={materials.AllColors_Material} position={[-25.29, 0, -4.48]} />
      <mesh geometry={nodes.Log_big_knotty.geometry} material={materials.AllColors_Material} position={[-16.08, 0, -4.48]} />
      <mesh geometry={nodes.Branch_average_bare.geometry} material={materials.AllColors_Material} position={[-21.76, 0, 5.4]} />
      <mesh geometry={nodes.Branch_average_leaves.geometry} material={materials.AllColors_Material} position={[-15.88, 0, 5.4]} />
      <mesh geometry={nodes.Stone_average_01.geometry} material={materials.AllColors_Material} position={[-17.92, 0, 12.45]} />
      <mesh geometry={nodes.Stone_average_01_mossy.geometry} material={materials.AllColors_Material} position={[-15.39, 0, 12.45]} />
      <mesh geometry={nodes.Stone_group_average.geometry} material={materials.AllColors_Material} position={[-12.26, 0, 12.45]} />
      <mesh geometry={nodes.Stone_group_average_mossy.geometry} material={materials.AllColors_Material} position={[-8.93, 0, 12.45]} />
      <mesh geometry={nodes.Grass_bush_high_01.geometry} material={materials.AllColors_Material} position={[-23.41, 0, 8.59]} />
      <mesh geometry={nodes.Grass_bush_low_01.geometry} material={materials.AllColors_Material} position={[-20.84, 0, 8.59]} />
      <mesh geometry={nodes.Flower_bush_white.geometry} material={materials.AllColors_Material} position={[-20.83, 0, 10.61]} />
      <mesh geometry={nodes.Flower_bush_blue.geometry} material={materials.AllColors_Material} position={[-22.18, 0, 10.61]} />
      <mesh geometry={nodes.Flower_bush_red.geometry} material={materials.AllColors_Material} position={[-23.55, 0, 10.61]} />
      <mesh geometry={nodes.Mushroom_big_brown.geometry} material={materials.AllColors_Material} position={[-24.24, 0, 12.85]} />
      <mesh geometry={nodes.Mushroom_big_group_brown.geometry} material={materials.AllColors_Material} position={[-23.38, 0, 12.85]} />
      <mesh geometry={nodes.Mushroom_flat_white.geometry} material={materials.AllColors_Material} position={[-22.5, 0, 12.85]} />
      <mesh geometry={nodes.Mushroom_flat_group_white.geometry} material={materials.AllColors_Material} position={[-21.65, 0, 12.85]} />
      <mesh geometry={nodes.Mushroom_high_yellow.geometry} material={materials.AllColors_Material} position={[-20.97, 0, 12.85]} />
      <mesh geometry={nodes.Mushroom_high_group_yellow.geometry} material={materials.AllColors_Material} position={[-20.3, 0, 12.85]} />
    </group>
  )
}

useGLTF.preload('/forest_tree.glb')
